---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - main.yml

- include: install.yml
  tags:
    - development
    - docker
    - install

- include: config.yml
  tags:
    - development
    - docker
    - config

- include: service.yml
  tags:
    - development
    - docker
    - service

- include: service.yml
  tags:
    - development
    - docker
    - manage
